services:
  gateway:
    image: "caddy:latest"
    container_name: "gateway"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
  api:
    image: "ewenquim/gourmet:latest"
    container_name: "api"
    platform: linux/amd64
    env_file:
      - .env
    volumes:
      - ./api:/app/data

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  cadvisor:
    image: "gcr.io/cadvisor/cadvisor:latest"
    container_name: "cadvisor"
    privileged: true
    devices:
      - "/dev/kmsg"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command:
      - "--docker_only"
      - "--housekeeping_interval=10s"

  prometheus:
    image: "prom/prometheus:latest"
    container_name: "prometheus"
    user: "1000"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus

  grafana:
    image: "grafana/grafana:latest"
    container_name: "grafana"
    user: "1000"
    volumes:
      - ./grafana:/var/lib/grafana

  astro:
    image: "ewenquim/gourmet-astro:latest"
    container_name: "astro"

  nextjs:
    image: "ewenquim/gourmet-next:latest"
    container_name: "nextjs"

  alpha:
    image: "nginx:latest"
    container_name: "alpha"

  epsilon:
    image: "nginx:latest"
    container_name: "epsilon"

  zeta:
    image: "llsun/recipe-app:latest"
    container_name: "zeta"

  eta:
    image: "nginx:latest"
    container_name: "eta"

  kappa:
    image: "nginx:latest"
    container_name: "kappa"

  lambda:
    image: "nonouille/lambda-archi-web:latest"
    container_name: "lambda"

  mu:
    image: "clarabh/gourmet-frontend:latest"
    container_name: "mu"

  nu:
    image: "nginx:latest"
    container_name: "nu"

  pi:
    image: "nginx:latest"
    container_name: "pi"

  sigma:
    image: "tibomllr/sigma-cooking:latest"
    container_name: "sigma"

  tau:
    image: "nginx:latest"
    container_name: "tau"

  upsilon:
    image: "am0911/jaifaim:latest"
    container_name: "upsilon"

  chi:
    image: "magnoir/archiweb-td:latest"
    container_name: "chi"

  psi:
    image: "nginx:latest"
    container_name: "psi"

  omega:
    image: "ankydios/cooking-madness:latest"
    container_name: "omega"

volumes:
  data:
